# Generated by Django 5.1.15 on 2026-09-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarfacility',
            name='case_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
